# Generated by Django 5.2 on 2025-04-28 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_question_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Home.chapter'),
        ),
    ]
